repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9 # We should always pin the commit hash and not the version, which can be exploited
    hooks:
      - id: check-ast
      - id: fix-byte-order-marker
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
       - id: mypy
         name: mypy
         files: '^.*\.py?$'
         entry: mypy --install-types --non-interactive
         exclude: ^.*\b(alembic|\.venv|\venv|tests)\b.*$
         additional_dependencies: [
           "sqlalchemy[mypy]"
         ]

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: 2b275ea7e0241bf601527d8378dc68d6e31e03e0 # We should always pin the commit hash and not the version, which can be exploited
    hooks:
      - id: absolufy-imports

  - repo: https://github.com/pycqa/isort
    rev: e44834b7b294701f596c9118d6c370f86671a50d # We should always pin the commit hash and not the version, which can be exploited
    hooks:
      - id: isort
        args: [ "--overwrite-in-place" ]
        stages: [pre-commit]

  - repo: https://github.com/psf/black
    rev: b0d1fba7ac3be53c71fb0d3211d911e629f8aecb # We should always pin the commit hash and not the version, which can be exploited
    hooks:
      - id: black
        args: [ "--line-length=120" ]
        stages: [pre-commit]

  - repo: https://github.com/pycqa/flake8
    rev: b9a7794c4f425ef8419081e6993f99419cc667ea # We should always pin the commit hash and not the version, which can be exploited
    hooks:
      - id: flake8
        args: [ "--max-line-length=120", "--ignore=E203,E501,W503" ]
