"""add orders table

Revision ID: f8d66dc4cc71
Revises: 62bdd93a4a70
Create Date: 2024-12-07 20:35:05.637582

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f8d66dc4cc71"
down_revision: Union[str, None] = "62bdd93a4a70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("id", mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
